In [1]:
import numpy as np

In [2]:
#creation of numpy array
x=np.array([1,2,3,4,5])
print(x)
print(type(x))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#shape and size
print(x.size)#total no. of element
print(x.shape)#dimensions of data
print(x.ndim)#num of dimensions

5
(5,)
1


In [7]:
x2d=np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.size)#total no. of element
print(x2d.shape)#dimensions of data
print(x2d.ndim)#num of dimensions

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [11]:
x25=np.random.randint(1,100,(5,5))
print(x25)

[[44 22 79 66 27]
 [15 48 61 52 81]
 [35 42  6 66 10]
 [15 68  2 67 15]
 [18 45 68 82 61]]


In [19]:
xseq1=np.arange(1,101,4)
print("----1 D matrix---")
print(xseq1)
print("---1 D matrix reshaped to 2 D---")
print(xseq1.size)

print(xseq1.reshape(5,5))

----1 D matrix---
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
---1 D matrix reshaped to 2 D---
25
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [22]:
xseq2=np.linspace(1,100,50)
print(xseq2.size,"elements")
print("----1 D matrix---")
print(xseq2)
print("---1 D matrix reshaped to 2 D---")
print(xseq2.reshape(10,5))
print("---1 D matrix reshaped to 3 D---")

print(xseq2.reshape(5,5,2))

50 elements
----1 D matrix---
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
---1 D matrix reshaped to 2 D---
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41

In [23]:
xseq2d=xseq2.reshape(10,5)
print(xseq2d)

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673]
 [ 61.6122449   63.63265306  65.65306122  67.67346939  69.69387755]
 [ 71.71428571  73.73469388  75.75510204  77.7755102   79.79591837]
 [ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918]
 [ 91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


In [25]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* indexing and slicing
* boolean filter
* maths and stats
* methods

In [26]:
x25

array([[44, 22, 79, 66, 27],
       [15, 48, 61, 52, 81],
       [35, 42,  6, 66, 10],
       [15, 68,  2, 67, 15],
       [18, 45, 68, 82, 61]])

In [27]:
# first row
print(x25[0])

[44 22 79 66 27]


In [28]:
# last row
print(x25[-1])

[18 45 68 82 61]


In [29]:
#single element
print(x25[0,1])# same as print(x25[0][1])

22


In [30]:
# 1 column
print(x25[:,0])
# 2nd column
print(x25[:,1])
# last columns
print(x25[:,-1])

[44 15 35 15 18]
[22 48 42 68 45]
[27 81 10 15 61]


In [31]:
# column 0 and 1 index
print(x25[:,[0,1]])

[[44 22]
 [15 48]
 [35 42]
 [15 68]
 [18 45]]


In [33]:
# column 0 and 1, 2 index
print(x25[:,[0,1,2]])
# same hings as above
print(x25[:,:3])

[[44 22 79]
 [15 48 61]
 [35 42  6]
 [15 68  2]
 [18 45 68]]
[[44 22 79]
 [15 48 61]
 [35 42  6]
 [15 68  2]
 [18 45 68]]


In [36]:
#filtering data without numpy boolean filter(bad idea)
for i in x25:
    for j in i:
        if j<=20:
            print(j)

15
6
10
15
2
15
18


In [37]:
x25<=20#boolean filter

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False, False, False, False]])

In [38]:
x25[x25<=20]

array([15,  6, 10, 15,  2, 15, 18])

In [39]:
x25[x25>50]

array([79, 66, 61, 52, 81, 66, 68, 67, 68, 82, 61])

In [40]:
(x25>20) & (x25<70)

array([[ True,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True,  True, False,  True]])

In [41]:
x25[(x25>20) & (x25<70)]

array([44, 22, 66, 27, 48, 61, 52, 35, 42, 66, 68, 67, 45, 68, 61])

In [42]:
np.append(x25,[1,2,3,4,5])# not as expected as damaging the shape og 5*5 order matrix

array([44, 22, 79, 66, 27, 15, 48, 61, 52, 81, 35, 42,  6, 66, 10, 15, 68,
        2, 67, 15, 18, 45, 68, 82, 61,  1,  2,  3,  4,  5])

In [47]:
np.append(x25,np.array([[1,2,3,4,5]]),axis=0)

array([[44, 22, 79, 66, 27],
       [15, 48, 61, 52, 81],
       [35, 42,  6, 66, 10],
       [15, 68,  2, 67, 15],
       [18, 45, 68, 82, 61],
       [ 1,  2,  3,  4,  5]])

In [59]:
a=np.random.randint(5,80,(2,3))
print(a)
print(a.shape)

[[18 66 28]
 [79 70 48]]
(2, 3)


In [60]:
b=np.random.randint(5,80,(3,2))
print(b)
print(b.shape)

[[11 15]
 [76 23]
 [65 27]]
(3, 2)


In [61]:
a.transpose()

array([[18, 79],
       [66, 70],
       [28, 48]])

In [62]:
print(np.hstack((a,b.T)))

[[18 66 28 11 76 65]
 [79 70 48 15 23 27]]


In [63]:
print(np.hstack((a.T,b)))

[[18 79 11 15]
 [66 70 76 23]
 [28 48 65 27]]


In [64]:
print(np.vstack((a.T,b)))
print(np.vstack((a,b.T)))

[[18 79]
 [66 70]
 [28 48]
 [11 15]
 [76 23]
 [65 27]]
[[18 66 28]
 [79 70 48]
 [11 76 65]
 [15 23 27]]
